# Generated by Django 4.2.11 on 2024-05-23 22:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lastName_P', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lastName_M', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'UsuariosInit',
                'verbose_name_plural': 'UsuariosInit',
                'db_table': 'user',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversaciones',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'conversations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIntention', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Intenciones',
                'verbose_name_plural': 'Intenciones',
                'db_table': 'intents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPhrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('intention', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.intents')),
            ],
            options={
                'verbose_name': 'FrasesDeEntrenamiento',
                'verbose_name_plural': 'FrasesDeEntrenamiento',
                'db_table': 'trainingPhrases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('intention', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.intents')),
            ],
            options={
                'verbose_name': 'Respuestas',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'responses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('conversation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.conversations')),
                ('senderUser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensajes',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'messages',
                'ordering': ['id'],
            },
        ),
    ]
