# Generated by Django 4.2.11 on 2024-05-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIntention', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('intention', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.intents')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('intention', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.intents')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('conversation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.conversations')),
                ('senderUser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.AddField(
            model_name='conversations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
