# Generated by Django 4.2.11 on 2024-06-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='intention',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='response',
        ),
        migrations.AddField(
            model_name='responses',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='descripcion_problema',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='solucion_sugerida',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='subcategoria',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='texto_consulta',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
